'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Crosshair, Volume2, VolumeX, Maximize, ChevronRight, Shield, Zap, Heart, Rocket, Orbit, Gem, Pause, Play, RotateCcw, Settings2, Trophy, X, Radio, Flame, Snowflake, Wind } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { Switch } from '@/components/ui/switch';
import { Slider } from '@/components/ui/slider';
import { SHIPS, WEAPONS, SECTORS, UPGRADES, ACHIEVEMENTS, freshSave } from '@/lib/game/content';
import { Simulation, loadSave } from '@/lib/game/simulation';
import { GameAudio } from '@/lib/game/audio';
import type { SpaceRenderer } from '@/lib/game/renderer';
import type { ShipId, WeaponId, GameInput, SaveData } from '@/lib/game/types';

const SAVE_KEY = 'voidbreaker-save-v1';
const clock = (s:number) => `${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const icons:Record<string,typeof Zap>={flame:Flame,zap:Zap,heart:Heart,shield:Shield,rocket:Rocket,orbit:Orbit,gem:Gem,radio:Radio,snow:Snowflake,wind:Wind,crosshair:Crosshair};
export default function Home() {
 const host=useRef<HTMLDivElement>(null), sim=useRef(new Simulation()), renderer=useRef<SpaceRenderer|null>(null), audio=useRef<GameAudio|null>(null), saveRef=useRef(freshSave());
 const keys=useRef(new Set<string>()), mouse=useRef({x:0,y:0,down:false,moved:false}), touch=useRef({x:0,y:0,active:false}), actions=useRef({dash:false,pulse:false});
 const [,tick]=useState(0);const [ready,setReady]=useState(false),[error,setError]=useState(''),[panel,setPanel]=useState<'settings'|'archive'|null>(null),[difficulty,setDifficulty]=useState<'normal'|'hard'>('normal');const [result,setResult]=useState({earned:0,achievements:[] as string[]});
 const refresh=()=>tick(x=>x+1);
 const persist=(data:SaveData)=>{saveRef.current=data;try{localStorage.setItem(SAVE_KEY,JSON.stringify(data));}catch{}refresh();};
 const changeSettings=(patch:Partial<SaveData['settings']>)=>{const data={...saveRef.current,settings:{...saveRef.current.settings,...patch}};persist(data);audio.current?.setMuted(data.settings.muted);audio.current?.setVolume(data.settings.volume);if(patch.quality)renderer.current?.setQuality(patch.quality);};
 const start=()=>{sim.current=new Simulation(saveRef.current.ship,saveRef.current.weapon,saveRef.current,Date.now(),difficulty);sim.current.start();keys.current.clear();mouse.current.down=false;touch.current={x:0,y:0,active:false};setPanel(null);setResult({earned:0,achievements:[]});void audio.current?.unlock();audio.current?.setScene('combat');refresh();};
 const hangar=()=>{sim.current=new Simulation(saveRef.current.ship,saveRef.current.weapon,saveRef.current);setPanel(null);keys.current.clear();audio.current?.setScene('menu');refresh();};
 useEffect(()=>{
  let stopped=false,frame=0;try{saveRef.current=loadSave(localStorage.getItem(SAVE_KEY));}catch{}sim.current=new Simulation(saveRef.current.ship,saveRef.current.weapon,saveRef.current);
  const sound=new GameAudio();audio.current=sound;sound.setVolume(saveRef.current.settings.volume);sound.setMuted(saveRef.current.settings.muted);
  import('@/lib/game/renderer').then(({SpaceRenderer})=>{if(stopped||!host.current)return;try{renderer.current=new SpaceRenderer(host.current,saveRef.current.settings.quality);setReady(true);}catch(e){setError('WebGL konnte nicht starten. Öffne das Spiel in einem Browser mit aktivierter Hardwarebeschleunigung.');console.error(e);}}).catch(()=>setError('Die Spielgrafik konnte nicht geladen werden. Bitte lade die Seite neu.'));
  const keydown=(e:KeyboardEvent)=>{if(['INPUT','TEXTAREA'].includes((e.target as HTMLElement)?.tagName))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.current.add(e.code);if(e.repeat)return;if(e.code==='Escape'){if(sim.current.state.phase==='playing')sim.current.pause();else if(sim.current.state.phase==='paused')sim.current.resume();refresh();}if(e.code==='Space')actions.current.dash=true;if(e.code==='KeyQ')actions.current.pulse=true;if(e.code==='KeyF'){sim.current.toggleAutoFire();saveRef.current.settings.autoFire=sim.current.state.autoFire;refresh();}if(sim.current.state.phase==='upgrade'&&['Digit1','Digit2','Digit3'].includes(e.code)){const c=sim.current.state.choices[Number(e.code.slice(-1))-1];if(c)sim.current.chooseUpgrade(c.id);refresh();}};
  const keyup=(e:KeyboardEvent)=>keys.current.delete(e.code);const move=(e:PointerEvent)=>{if(e.pointerType==='touch')return;mouse.current={...mouse.current,x:e.clientX,y:e.clientY,moved:true};};const down=(e:PointerEvent)=>{if((e.target as HTMLElement).closest('button,a,[role="slider"],.overlay'))return;if(e.button===0)mouse.current.down=true;};const up=()=>{mouse.current.down=false;};
  const blur=()=>{keys.current.clear();mouse.current.down=false;touch.current={x:0,y:0,active:false};actions.current={dash:false,pulse:false};sim.current.pause();sound.setScene('quiet');refresh();};
  const visibility=()=>{if(document.hidden)blur();};
  window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('pointermove',move);window.addEventListener('pointerdown',down);window.addEventListener('pointerup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);
  let last=performance.now(),ui=0,accumulator=0,lastPhase='menu';
  const loop=(now:number)=>{if(stopped)return;const dt=Math.min(.1,(now-last)/1000);last=now;const g=sim.current,s=g.state;let aim={x:s.player.x,y:s.player.y-20};if(mouse.current.moved&&renderer.current)aim=renderer.current.aim(mouse.current.x,mouse.current.y);if(touch.current.active){let nearest=Infinity;for(const e of s.enemies){const d=Math.hypot(e.x-s.player.x,e.y-s.player.y);if(d<nearest){nearest=d;aim={x:e.x,y:e.y};}}}
   const input:GameInput={x:touch.current.x+(keys.current.has('KeyD')||keys.current.has('ArrowRight')?1:0)-(keys.current.has('KeyA')||keys.current.has('ArrowLeft')?1:0),y:touch.current.y+(keys.current.has('KeyS')||keys.current.has('ArrowDown')?1:0)-(keys.current.has('KeyW')||keys.current.has('ArrowUp')?1:0),aimX:aim.x,aimY:aim.y,firing:mouse.current.down||touch.current.active,dash:actions.current.dash,pulse:actions.current.pulse};
   accumulator+=dt;while(accumulator>=1/60){g.step(1/60,input);input.dash=false;input.pulse=false;accumulator-=1/60;}actions.current={dash:false,pulse:false};
   for(const event of g.events)sound.play(event.type,event.value);g.events=[];
   if(s.phase!==lastPhase){lastPhase=s.phase;sound.setScene(s.phase==='playing'?(s.wave===4?'boss':'combat'):s.phase==='menu'?'menu':'quiet');if(s.phase==='victory'||s.phase==='defeat'){const ended=g.finish(saveRef.current);persist(ended.save);setResult({earned:ended.earned,achievements:ended.achievements});}refresh();}
   if(s.phase==='playing')sound.setScene(s.wave===4?'boss':'combat');sound.setIntensity(Math.min(1,s.enemies.length/25+s.sector*.15));sound.update(dt);renderer.current?.render(s,dt,saveRef.current.settings.shake);ui+=dt;if(ui>.1){ui=0;refresh();}frame=requestAnimationFrame(loop);
  };frame=requestAnimationFrame(loop);
  const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;const lifecycle=new AbortController();if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'get_voidbreaker_status',description:'Read current game phase, sector, hull and score.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({phase:sim.current.state.phase,sector:sim.current.state.sector+1,hull:sim.current.state.player.hp,score:sim.current.score()})},{signal:lifecycle.signal})).catch(()=>{});}catch{}}
  return()=>{stopped=true;cancelAnimationFrame(frame);lifecycle.abort();renderer.current?.dispose();renderer.current=null;sound.dispose();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('pointermove',move);window.removeEventListener('pointerdown',down);window.removeEventListener('pointerup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);};
 },[]);
 const s=sim.current.state,p=s.player,save=saveRef.current,ship=save.ship,weapon=save.weapon,selected=SHIPS.find(x=>x.id===ship)!;const menu=s.phase==='menu';const boss=s.enemies.find(e=>e.kind==='boss');
 const option=(id:ShipId)=>{persist({...save,ship:id});sim.current.state.ship=id;audio.current?.play('click');};
 const icon=(name:string,size=24)=>{const Icon=icons[name]||Crosshair;return <Icon size={size}/>;};
 const openPanel=(value:'settings'|'archive')=>{sim.current.pause();setPanel(value);refresh();};
 const joystick=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)/35,y=(e.clientY-r.top-r.height/2)/35;touch.current={x:Math.max(-1,Math.min(1,x)),y:Math.max(-1,Math.min(1,y)),active:true};};
 return <main className={`game-shell ${menu?'':'in-game'}`}><div ref={host} className="space-view"/><div className="vignette"/>
  <header className="topbar"><button className="brand" aria-label="Hangar" onClick={()=>{if(menu)setPanel(null);else{sim.current.pause();refresh();}}}><Crosshair size={20}/><span>VB<span className="brand-dot">/</span></span></button><span className="top-label">{menu?'FLUGSYSTEM 09.04':`SEKTOR 0${s.sector+1} / ${SECTORS[s.sector].name}`} <i/> {menu?'VERBINDUNG AKTIV':clock(s.totalTime)}</span><div className="top-actions">{!menu&&<Button variant="ghost" size="icon" aria-label="Pause" onClick={()=>{sim.current.pause();refresh();}}><Pause/></Button>}<Button variant="ghost" size="icon" aria-label={save.settings.muted?'Ton einschalten':'Ton ausschalten'} onClick={()=>{void audio.current?.unlock();changeSettings({muted:!save.settings.muted});}}>{save.settings.muted?<VolumeX/>:<Volume2/>}</Button><Button variant="ghost" size="icon" aria-label="Einstellungen" onClick={()=>openPanel('settings')}><Settings2/></Button><Button variant="ghost" size="icon" aria-label="Vollbild" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen?.().catch(()=>{});else void document.documentElement.requestFullscreen?.().catch(()=>{});}}><Maximize/></Button></div></header>
  {error&&<div className="error-notice">{error}</div>}
  {menu&&<><section className="hangar-copy"><div className="eyebrow"><span/> EIN SIGNAL. EINE LETZTE CHANCE.</div><h1>VOID<br/><span>BREAKER</span><b>®</b></h1><p className="intro">Die Tore sind verstummt.<br/>Bring das letzte Licht durch die Leere.</p><Button className="launch" disabled={!ready} onClick={start}>{ready?'EINSATZ STARTEN':'SYSTEME STARTEN…'} <ArrowUpRight size={22}/></Button><div className="launch-note">3 SEKTOREN <span>·</span> EIN LEBEN <span>·</span> DEIN BUILD</div><button className="archive-link" onClick={()=>openPanel('archive')}><Trophy size={13}/> FLUGARCHIV <span>{save.shards} KERNSPLITTER</span></button></section><div className="ship-caption"><span>0{SHIPS.findIndex(x=>x.id===ship)+1} / FLUGBEREIT</span><h2>{selected.name}</h2><p>{selected.role}</p><div className="caption-line"/><div className="ship-spec"><span>HÜLLE {selected.hp}</span><span>SCHILD {selected.shield}</span></div></div>
  <section className="hangar-bottom"><div className="loadout-head"><span>DEIN SCHIFF</span><button onClick={()=>setDifficulty(difficulty==='normal'?'hard':'normal')}>MODUS: {difficulty==='normal'?'PILOT':'VETERAN'} ↗</button><span>HANGAR / 03 EINHEITEN</span></div><Tabs value={ship} onValueChange={v=>option(v as ShipId)}><TabsList className="ship-list">{SHIPS.map((x,i)=><TabsTrigger className="ship-card" value={x.id} key={x.id}><span className="ship-num">0{i+1}</span><div><strong>{x.name}</strong><small>{x.role}</small></div><ChevronRight size={16}/></TabsTrigger>)}</TabsList></Tabs><div className="hangar-bottom-row"><div className="weapon-select">{WEAPONS.map(w=><button key={w.id} title={w.description} onClick={()=>persist({...save,weapon:w.id})} className={weapon===w.id?'selected':''}><Crosshair size={13}/>{w.name}</button>)}</div><div className="controls-hint"><kbd>W A S D</kbd> FLIEGEN <kbd>MAUS</kbd> ZIELEN <kbd>SPACE</kbd> DASH</div></div></section></>}
  {!menu&&<><div className="pilot-hud"><div className="pilot-name">{SHIPS.find(x=>x.id===s.ship)?.name}<span>LVL {p.level}</span></div><div className="bar-label"><Heart size={13}/> HÜLLE <b>{Math.ceil(p.hp)} / {p.maxHp}</b></div><Progress aria-label="Hülle" className="hull-bar" value={p.hp/p.maxHp*100}/><div className="bar-label shield-label"><Shield size={13}/> SCHILD <b>{Math.ceil(p.shield)} / {p.maxShield}</b></div><Progress aria-label="Schild" className="shield-bar" value={p.shield/p.maxShield*100}/><div className="hud-resources"><Gem size={13}/>{s.stats.scrap}<span>{s.stats.kills} ABSCHÜSSE</span></div></div><div className="wave-hud"><span>{s.wave===4?'SEKTORBOSS':`WELLE 0${s.wave} / 03`}</span><strong>{s.wave===4?'KERN ZERSTÖREN':s.intermission>0?'BERGUNG AKTIV':s.waveTime>=s.waveDuration?`${s.enemies.length} ZIELE VERBLEIBEND`:`${Math.max(0,Math.ceil(s.waveDuration-s.waveTime))}s`}</strong><small>{s.combo>=3?`${s.combo} × ABSCHUSSSERIE`:'BLEIB IN BEWEGUNG'}</small></div>
  {boss&&<div className="boss-hud"><div><span>{SECTORS[s.sector].bossName}</span><small>PHASE {boss.bossPhase}</small></div><Progress aria-label="Boss-Hülle" value={boss.hp/boss.maxHp*100}/></div>}
  {s.bannerTime>0&&s.phase==='playing'&&<div className="game-banner" key={s.banner}><span>{s.bannerSub}</span><h2>{s.banner}</h2></div>}
  <div className="bottom-hud"><div className="weapon-hud"><Crosshair size={19}/><div>{WEAPONS.find(w=>w.id===s.weapon)?.name}<button onClick={()=>{sim.current.toggleAutoFire();refresh();}}>DAUERFEUER {s.autoFire?'AN':'AUS'} <kbd>F</kbd></button></div></div><div className="abilities"><button onClick={()=>{actions.current.dash=true;}} className={p.dashCooldown<=0?'charged':''}><Wind size={21}/><span>DASH</span><kbd>SPACE</kbd><small>{p.dashCooldown<=0?'BEREIT':`${p.dashCooldown.toFixed(1)}s`}</small></button><button onClick={()=>{actions.current.pulse=true;}} className={p.pulse>=100?'charged':''}><Radio size={21}/><span>NULLIMPULS</span><kbd>Q</kbd><small>{p.pulse>=100?'BEREIT':`${Math.floor(p.pulse)} %`}</small></button></div><div className="minimap"><svg viewBox="-55 -55 110 110" aria-label="Radar"><circle r="51" fill="none" stroke="#456665" strokeWidth=".6"/><circle r="26" fill="none" stroke="#254443" strokeWidth=".5"/><path d="M-51 0H51M0 -51V51" stroke="#254443" strokeWidth=".5"/>{s.enemies.map(e=><circle key={e.id} cx={e.x} cy={e.y} r={e.kind==='boss'?3:1.4} fill="#ff946e"/>)}<circle cx={p.x} cy={p.y} r="2.6" fill="#c5ff72"/></svg></div></div><div className="xp-strip"><Progress aria-label="Erfahrung" value={p.xp/p.nextXp*100}/></div><div className="build-strip">{Object.entries(s.upgrades).filter(([,n])=>n).map(([id,n])=><span key={id} title={UPGRADES.find(u=>u.id===id)?.name}>{icon(UPGRADES.find(u=>u.id===id)?.icon||'',14)}<b>{n}</b></span>)}</div>
  {s.phase==='playing'&&<div className="touch-stick" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);joystick(e);}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))joystick(e);}} onPointerUp={()=>{touch.current={x:0,y:0,active:false};}} onPointerCancel={()=>{touch.current={x:0,y:0,active:false};}}><div/>FLIEGEN</div>}
  {s.totalTime<12&&s.phase==='playing'&&<div className="tutorial"><kbd>WASD</kbd> Fliegen · Maus zielen · <kbd>SPACE</kbd> Unverwundbar dashen · <kbd>Q</kbd> EMP bei 100 %</div>}
  </>}
  {s.phase==='upgrade'&&!panel&&<section className="overlay"><div className="dialog-content wide"><div className="eyebrow"><span/> SYSTEMAUFWERTUNG / STUFE {p.level}</div><h2>MEHR ALS EIN SCHIFF.</h2><p>Wähle ein Modul. Dein Build verändert den nächsten Kampf.</p><div className="upgrade-grid">{s.choices.map((u,i)=><button className={`upgrade-card ${u.rarity}`} key={u.id} onClick={()=>{sim.current.chooseUpgrade(u.id);refresh();}}><span className="rarity">{u.rarity==='epic'?'EXOTISCH':u.rarity==='rare'?'SELTEN':'STANDARD'} <kbd>{i+1}</kbd></span><div className="upgrade-icon">{icon(u.icon,34)}</div><small>{u.category.toUpperCase()} · STUFE {(s.upgrades[u.id]||0)+1}/{u.max}</small><h3>{u.name}</h3><p>{u.description}</p><span className="install">INSTALLIEREN <ArrowUpRight size={18}/></span></button>)}</div><Button variant="outline" onClick={()=>{sim.current.reroll();refresh();}} disabled={s.rerolls<=0}><RotateCcw size={14}/> NEUE AUSWAHL ({s.rerolls})</Button><small className="pause-note">ZEIT ANGEHALTEN · WÄHLE IN RUHE</small></div></section>}
  {s.phase==='station'&&!panel&&<section className="overlay"><div className="dialog-content wide"><div className="eyebrow"><span/> SEKTOR 0{s.sector+1} GESICHERT</div><h2>EIN MOMENT STILLE.</h2><p>{SECTORS[s.sector+1].narrative}</p><div className="station-balance"><Gem size={18}/>{s.stats.scrap} SCHROTT VERFÜGBAR</div><div className="upgrade-grid">{([{id:'repair',name:'Feldreparatur',text:'Repariert deine Hülle vollständig.',cost:40,icon:'heart'},{id:'module',name:'Schwarzmarkt-Modul',text:'Wähle eine zusätzliche Aufwertung aus drei Modulen.',cost:95,icon:'zap'},{id:'charge',name:'EMP-Kondensator',text:'Lädt deinen Nullimpuls auf 100 %.',cost:30,icon:'radio'}] as const).map(item=><button className="shop-card" key={item.id} disabled={s.stationBought.includes(item.id)||s.stats.scrap<item.cost||(item.id==='repair'&&p.hp>=p.maxHp)||(item.id==='charge'&&p.pulse>=100)} onClick={()=>{sim.current.purchase(item.id);refresh();}}>{icon(item.icon,28)}<h3>{item.name}</h3><p>{item.text}</p><strong>{s.stationBought.includes(item.id)?'INSTALLIERT':`${item.cost} SCHROTT`}</strong></button>)}</div><Button className="launch" onClick={()=>{sim.current.continueSector();refresh();}}>SPRUNG IN SEKTOR 0{s.sector+2}<ArrowUpRight/></Button></div></section>}
  {s.phase==='paused'&&!panel&&<section className="overlay"><div className="dialog-content"><div className="eyebrow"><span/> AUTOPILOT AKTIV</div><h2>ATEMPAUSE.</h2><p>Dein Schiff wartet auf dich.</p><Button className="launch" onClick={()=>{sim.current.resume();void audio.current?.unlock();refresh();}}>WEITERFLIEGEN <Play/></Button><Button variant="outline" onClick={()=>setPanel('settings')}><Settings2/> EINSTELLUNGEN</Button><Button variant="ghost" onClick={hangar}>Einsatz aufgeben · Zum Hangar</Button><div className="control-guide"><p><kbd>WASD / PFEILE</kbd> Fliegen</p><p><kbd>MAUS</kbd> Zielen · Linksklick feuern</p><p><kbd>F</kbd> Dauerfeuer umschalten</p><p><kbd>SPACE</kbd> Dash mit Unverwundbarkeit</p><p><kbd>Q</kbd> EMP löscht Projektile</p><p><kbd>ESC</kbd> Pause / Fortsetzen</p></div></div></section>}
  {(s.phase==='victory'||s.phase==='defeat')&&!panel&&<section className="overlay"><div className="dialog-content wide"><div className="eyebrow"><span/> {s.phase==='victory'?'SIGNAL WIEDERHERGESTELLT':'SIGNAL VERLOREN'}</div><h2>{s.phase==='victory'?'DAS LETZTE LICHT.':'NOCH NICHT DAS ENDE.'}</h2><p>{s.phase==='victory'?'Ein Ton wird zu Stimmen. Die Tore öffnen sich. Du hast uns nach Hause gebracht.':'Die Leere vergisst. Dein Hangar nicht. Beim nächsten Sprung bist du stärker.'}</p><div className="result-score">{sim.current.score().toLocaleString('de-CH')}<span>PUNKTE</span></div><div className="result-stats"><div><b>{s.stats.kills}</b>ABSCHÜSSE</div><div><b>{s.stats.bosses}/3</b>BOSSE</div><div><b>{clock(s.totalTime)}</b>FLUGZEIT</div><div><b>+{result.earned}</b>KERNSPLITTER</div></div>{result.achievements.length>0&&<p className="achievement-toast"><Trophy size={16}/> {result.achievements.map(id=>ACHIEVEMENTS.find(a=>a.id===id)?.name).join(' · ')}</p>}<div className="result-actions"><Button className="launch" onClick={start}>NOCH EIN SPRUNG <RotateCcw/></Button><Button variant="outline" onClick={hangar}>ZUM HANGAR</Button></div></div></section>}
  {panel&&<section className="overlay"><div className="dialog-content wide"><Button className="close-panel" variant="ghost" size="icon" aria-label="Schließen" onClick={()=>setPanel(null)}><X/></Button><div className="eyebrow"><span/> VOIDBREAKER / SYSTEME</div><h2>{panel==='settings'?'DEIN COCKPIT.':'DAS FLUGARCHIV.'}</h2>{panel==='settings'?<div className="settings-list"><label>Sound<Switch aria-label="Sound" checked={!save.settings.muted} onCheckedChange={v=>{void audio.current?.unlock();changeSettings({muted:!v});}}/></label><label>Lautstärke <span>{Math.round(save.settings.volume*100)} %</span></label><Slider aria-label="Lautstärke" value={[save.settings.volume*100]} min={0} max={100} onValueChange={v=>changeSettings({volume:(Array.isArray(v)?v[0]:v)/100})}/><label>Kameraerschütterung<Switch aria-label="Kameraerschütterung" checked={save.settings.shake} onCheckedChange={v=>changeSettings({shake:v})}/></label><label>Bloom & hohe Auflösung<Switch aria-label="Hohe Grafikqualität" checked={save.settings.quality==='high'} onCheckedChange={v=>changeSettings({quality:v?'high':'low'})}/></label><p>Bei niedriger Bildrate Bloom ausschalten. Fortschritt wird automatisch in diesem Browser gespeichert.</p></div>:<><div className="result-stats"><div><b>{save.totalRuns}</b>EINSÄTZE</div><div><b>{save.wins}</b>SIEGE</div><div><b>{save.bestScore.toLocaleString('de-CH')}</b>REKORD</div><div><b>{save.shards}</b>KERNSPLITTER</div></div><div className="meta-grid">{(['hull','damage','fortune'] as const).map((id,i)=>{const cost=40+save.meta[id]*35;return <button key={id} disabled={save.meta[id]>=5||save.shards<cost} onClick={()=>{if(saveRef.current.shards<cost)return;persist({...save,shards:save.shards-cost,meta:{...save.meta,[id]:save.meta[id]+1}});audio.current?.play('upgrade');}}><strong>{['VERSTÄRKTE HÜLLE','WAFFENKALIBRIERUNG','TAKTISCHER SCAN'][i]}</strong><p>{['+8 Hülle pro Stufe','+4 % Schaden pro Stufe','+1 neue Modulauswahl pro Stufe'][i]}</p><span>{save.meta[id]}/5 · {save.meta[id]>=5?'MAXIMUM':`${cost} SPLITTER`}</span></button>;})}</div><div className="achievements">{ACHIEVEMENTS.map(a=><div className={save.achievements.includes(a.id)?'unlocked':''} key={a.id}><Trophy size={18}/><div><strong>{a.name}</strong><p>{a.description}</p></div><span>+{a.reward}</span></div>)}</div></>}</div></section>}
 </main>;
}
