import type {
  EnemyKind,
  SectorDef,
  ShipDef,
  UpgradeDef,
  WeaponDef,
  SaveData,
} from './types';

export const SHIPS: ShipDef[] = [
  {
    id: 'kestrel',
    name: 'KESTREL',
    role: 'INTERCEPTOR',
    description:
      'Precise thrust vectors. Balanced firepower. Built to bring you home.',
    hp: 100,
    shield: 60,
    speed: 17,
    damage: 1,
    dash: 2.3,
    color: '#7bf4db',
    stats: [3, 3, 3],
    passive: '10% chance to land a critical hit.',
  },
  {
    id: 'wraith',
    name: 'WRAITH',
    role: 'PHANTOM CLASS',
    description: 'A shadow between salvos. Fast, fragile, lethal.',
    hp: 70,
    shield: 45,
    speed: 21,
    damage: 1.15,
    dash: 1.6,
    color: '#b09cff',
    stats: [5, 2, 4],
    passive: 'Fast dash recharge. +15% damage.',
  },
  {
    id: 'bastion',
    name: 'BASTION',
    role: 'HEAVY CRUISER',
    description: 'Holds the line. Heavy armor. Heavier firepower.',
    hp: 155,
    shield: 80,
    speed: 13.5,
    damage: 1.12,
    dash: 3.1,
    color: '#ffae66',
    stats: [2, 5, 4],
    passive: '+55 hull and reinforced shields.',
  },
];
export const WEAPONS: WeaponDef[] = [
  {
    id: 'pulse',
    name: 'PULSE LASER',
    description: 'Rapid, precise bursts',
    damage: 13,
    rate: 0.16,
    speed: 69,
    count: 1,
    spread: 0.018,
    pierce: 0,
    color: '#85ffe5',
  },
  {
    id: 'scatter',
    name: 'STARSHOT',
    description: 'Five projectiles. Get in close.',
    damage: 9,
    rate: 0.48,
    speed: 54,
    count: 5,
    spread: 0.13,
    pierce: 0,
    color: '#ffb573',
  },
  {
    id: 'rail',
    name: 'RAIL CANNON',
    description: 'Pierces up to four targets',
    damage: 55,
    rate: 0.73,
    speed: 115,
    count: 1,
    spread: 0,
    pierce: 3,
    color: '#bea4ff',
  },
];
export const SECTORS: SectorDef[] = [
  {
    name: 'THE DEBRIS BELT',
    subtitle: 'KEPLER–9 ORBIT',
    color: '#ff874f',
    bossName: 'THE COLLECTOR',
    narrative: 'The fleet made its last stand here. Find the jump core.',
  },
  {
    name: 'ION STORM',
    subtitle: 'THE BROKEN RELAY',
    color: '#78dacd',
    bossName: 'THE ARCHITECT',
    narrative:
      'The relay is still transmitting. Someone is waiting on the other side.',
  },
  {
    name: 'THE LAST LIGHT',
    subtitle: 'EVENT HORIZON',
    color: '#bc92ff',
    bossName: 'THE NULLHEART',
    narrative: 'The source of the signal. One last jump. Bring us home.',
  },
];
export const UPGRADES: UpgradeDef[] = [
  {
    id: 'damage',
    name: 'Hot Core',
    description: '+20% weapon damage. More energy in every shot.',
    max: 5,
    rarity: 'common',
    category: 'Weapon',
    icon: 'flame',
  },
  {
    id: 'firerate',
    name: 'Overclock',
    description: '+15% fire rate for your primary weapon.',
    max: 5,
    rarity: 'common',
    category: 'Weapon',
    icon: 'zap',
  },
  {
    id: 'multishot',
    name: 'Twin Barrels',
    description: '+1 projectile per shot. Extra barrels deal 70% damage.',
    max: 3,
    rarity: 'epic',
    category: 'Weapon',
    icon: 'split',
  },
  {
    id: 'pierce',
    name: 'Phase Rounds',
    description: 'Projectiles pierce one additional target.',
    max: 3,
    rarity: 'rare',
    category: 'Weapon',
    icon: 'arrow',
  },
  {
    id: 'crit',
    name: 'Weakpoint Scanner',
    description: '+10% critical hit chance. Critical hits deal double damage.',
    max: 5,
    rarity: 'common',
    category: 'Weapon',
    icon: 'crosshair',
  },
  {
    id: 'hull',
    name: 'Composite Armor',
    description: '+30 maximum hull. Instantly repairs 35 hull.',
    max: 4,
    rarity: 'common',
    category: 'System',
    icon: 'heart',
  },
  {
    id: 'shield',
    name: 'Shield Matrix',
    description: '+25 shield capacity. Instantly restores all shields.',
    max: 4,
    rarity: 'common',
    category: 'System',
    icon: 'shield',
  },
  {
    id: 'regen',
    name: 'Nanorepair',
    description: 'Repairs 4 hull every 8 seconds. Further ranks repair faster.',
    max: 3,
    rarity: 'rare',
    category: 'System',
    icon: 'heart',
  },
  {
    id: 'speed',
    name: 'Ion Drive',
    description: '+12% flight speed and +15% pickup radius.',
    max: 3,
    rarity: 'common',
    category: 'System',
    icon: 'wind',
  },
  {
    id: 'dash',
    name: 'Phase Dash',
    description: 'Dash recharges 20% faster and releases a damaging shockwave.',
    max: 3,
    rarity: 'rare',
    category: 'System',
    icon: 'wind',
  },
  {
    id: 'magnet',
    name: 'Tractor Beam',
    description: '+60% pickup radius. +15% experience from salvage.',
    max: 3,
    rarity: 'common',
    category: 'Tech',
    icon: 'magnet',
  },
  {
    id: 'salvage',
    name: 'Salvage Protocol',
    description: '+30% scrap from defeated enemies.',
    max: 3,
    rarity: 'common',
    category: 'Tech',
    icon: 'gem',
  },
  {
    id: 'missiles',
    name: 'Swarm Missiles',
    description: 'Fires a homing missile every 3 seconds. +1 missile per rank.',
    max: 4,
    rarity: 'rare',
    category: 'Tech',
    icon: 'rocket',
  },
  {
    id: 'drones',
    name: 'Escort Drone',
    description:
      'An autonomous combat drone follows you and fires at nearby targets.',
    max: 3,
    rarity: 'rare',
    category: 'Tech',
    icon: 'drone',
  },
  {
    id: 'orbitals',
    name: 'Orbital Blades',
    description: 'Two orbiting blades damage nearby enemies.',
    max: 3,
    rarity: 'rare',
    category: 'Tech',
    icon: 'orbit',
  },
  {
    id: 'chain',
    name: 'Chain Reactor',
    description: 'Hits have a 20% chance to arc to 2 nearby enemies.',
    max: 3,
    rarity: 'epic',
    category: 'Weapon',
    icon: 'zap',
  },
  {
    id: 'explode',
    name: 'Supernova',
    description: 'Defeated enemies explode, dealing 22 area damage.',
    max: 3,
    rarity: 'epic',
    category: 'Weapon',
    icon: 'sun',
  },
  {
    id: 'freeze',
    name: 'Cryoplasma',
    description: 'Hits slow enemies by 35% for 2 seconds.',
    max: 2,
    rarity: 'rare',
    category: 'Weapon',
    icon: 'snow',
  },
  {
    id: 'lifesteal',
    name: 'Reclamation',
    description: 'Every 15 kills repairs 5 hull. Further ranks restore more.',
    max: 3,
    rarity: 'rare',
    category: 'System',
    icon: 'heart',
  },
  {
    id: 'pulse',
    name: 'Event Horizon',
    description: '+35% EMP damage and +25% EMP energy from kills.',
    max: 3,
    rarity: 'rare',
    category: 'System',
    icon: 'radio',
  },
  {
    id: 'overdrive',
    name: 'Glass Cannon',
    description: '+35% damage, but −15 maximum hull. A dangerous trade.',
    max: 3,
    rarity: 'epic',
    category: 'Weapon',
    icon: 'flame',
  },
  {
    id: 'ricochet',
    name: 'Ricochet',
    description: 'Hits have a 35% chance to fire at an additional target.',
    max: 2,
    rarity: 'rare',
    category: 'Weapon',
    icon: 'split',
  },
];
export const ENEMY_DATA: Record<
  EnemyKind,
  {
    hp: number;
    speed: number;
    damage: number;
    radius: number;
    xp: number;
    color: string;
    name: string;
  }
> = {
  drone: {
    hp: 30,
    speed: 8,
    damage: 12,
    radius: 1.2,
    xp: 5,
    color: '#ff865a',
    name: 'Seeker Drone',
  },
  striker: {
    hp: 55,
    speed: 6,
    damage: 18,
    radius: 1.5,
    xp: 9,
    color: '#ff575f',
    name: 'Striker',
  },
  gunner: {
    hp: 46,
    speed: 4.5,
    damage: 12,
    radius: 1.3,
    xp: 10,
    color: '#ffba68',
    name: 'Gunner',
  },
  bomber: {
    hp: 75,
    speed: 3.8,
    damage: 17,
    radius: 1.8,
    xp: 16,
    color: '#da87ef',
    name: 'Minelayer',
  },
  warden: {
    hp: 165,
    speed: 3.6,
    damage: 20,
    radius: 2.5,
    xp: 25,
    color: '#ff7357',
    name: 'Warden',
  },
  swarm: {
    hp: 13,
    speed: 12,
    damage: 7,
    radius: 0.7,
    xp: 3,
    color: '#fba073',
    name: 'Swarm',
  },
  boss: {
    hp: 2400,
    speed: 3.5,
    damage: 20,
    radius: 5.5,
    xp: 140,
    color: '#ff8552',
    name: 'Sector Core',
  },
  lancer: { hp: 62, speed: 4.8, damage: 19, radius: 1.35, xp: 13, color: '#ffe08a', name: 'Needle Lancer' },
  brood: { hp: 135, speed: 2.8, damage: 15, radius: 2.2, xp: 24, color: '#a5f789', name: 'Brood Ark' },
  manta: { hp: 72, speed: 8, damage: 12, radius: 1.7, xp: 15, color: '#82d8ff', name: 'Veil Manta' },
  anchor: { hp: 95, speed: 3.3, damage: 24, radius: 1.65, xp: 20, color: '#f795d9', name: 'Rift Anchor' },
};
export const ACHIEVEMENTS = [
  {
    id: 'first',
    name: 'First Contact',
    description: 'Complete your first run.',
    reward: 15,
  },
  {
    id: 'hunter',
    name: 'Bounty Hunter',
    description: 'Destroy 100 enemies across all runs.',
    reward: 25,
  },
  {
    id: 'ace',
    name: 'Fleet Ace',
    description: 'Destroy 500 enemies across all runs.',
    reward: 50,
  },
  {
    id: 'boss',
    name: 'Boundary Breaker',
    description: 'Defeat a sector boss.',
    reward: 30,
  },
  {
    id: 'win',
    name: 'The Last Light',
    description: 'Defeat the Chronovore.',
    reward: 100,
  },
  {
    id: 'combo',
    name: 'Unstoppable',
    description: 'Reach a 25-kill combo.',
    reward: 35,
  },
];
export const freshSave = (): SaveData => ({
  version: 1,
  shards: 0,
  totalRuns: 0,
  wins: 0,
  bestScore: 0,
  bestSector: 0,
  totalKills: 0,
  ship: 'kestrel',
  weapon: 'pulse',
  meta: { hull: 0, damage: 0, fortune: 0 },
  achievements: [],
  settings: {
    volume: 0.45,
    muted: false,
    shake: true,
    quality: 'high',
    autoFire: true,
  },
});
